delete from tips;
delete from checkins;
delete from userfriends;
delete from users;
delete from businessattributes;
delete from businesscategories;
delete from businesses;
delete from attributes;
delete from categories;
